// <auto-generated />
namespace WcfServiceEAP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Employee_EAP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employee_EAP));
        
        string IMigrationMetadata.Id
        {
            get { return "202202240245218_Employee_EAP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
